Algoritmo "Exercicio 3" //Conversor Celsius para Fahrenheit
Var
// Seção de Declarações das variáveis 
   graus_c, graus_f: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Informe a temperatura em grau Celsius: ")
   leia(graus_c)
   
   graus_f <- (9/5)*graus_c+32

   escreva("A conversão de grau Celsius p/ graus Fahrenheit é: ", graus_f)

Fimalgoritmo
