Algoritmo "Exercicio 5" //tamanho da area (largura/comprimento)
Var
// Seção de Declarações das variáveis 
   larg, comp, tam_area: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite a Largura: ")
   leia(larg)
   
   escreva("Digite o comprimento: ")
   leia(comp)
   
   tam_area <- larg*comp
   
   escreva ("O tamanho da area em m² é: ", tam_area)
   
Fimalgoritmo
