Algoritmo "Exercicio 2" //conversor dolar
Var
// Seção de Declarações das variáveis 
   cota_dolar, qtd_dolar, convert: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite a cotação do dolar atual: ")
   leia(cota_dolar)
   
   escreva("Digite uma quantia de dolares para conversão: ")
   leia(qtd_dolar)
   
   convert <- cota_dolar*qtd_dolar
   
   escreval("A conversão de dolar para real fica: ", convert)

Fimalgoritmo
