algoritmo "Exercicio 1"
var
   n, i: inteiro
inicio

      escreva("Digite um numero: ")
      leia(n)

      enquanto n <> 0 faca
               //n <- n+1
               para i de n ate 19 faca //se (n > 0)
                      n <- n+1
                    escreval(n)
               fimpara
      escreva("Digite um numero: ")
      leia(n)

      fimenquanto
      
      escreval(n)
      
fimalgoritmo
